apiVersion: apps/v1
kind: Deployment
metadata:
  name: dias-online
  namespace: default
  labels:
    app: dias-online
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dias-online
  template:
    metadata:
      labels:
        app: dias-online
    spec:
      containers:
      - name: php-fpm
        image: localhost:32000/dias-online:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: fpm
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html
          readOnly: true
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
      volumes:
      - name: app-code
        hostPath:
          path: /home/nmwtech/sites/dias-online
          type: Directory
