apiVersion: v1
kind: Service
metadata:
  name: dias-online
  namespace: default
  labels:
    app: dias-online
spec:
  type: ClusterIP
  selector:
    app: dias-online
  ports:
  - name: fpm
    port: 9000
    targetPort: 9000
